HTML/CSS初級アウトプット課題
yokoyamamn/hc_practice pull request #2
Opened 2023-07-24 04:36 UTC by yokoyamamn

ご確認いただけますと幸いです。

2023-07-24 04:45 UTC, ihatov08 requested changes
横スクロールバーが表示されないように修正お願いします
スマホ対応をお願いします！

2023-07-24 23:30 UTC, yokoyamamn commented
@ihatov08 
課題の仕様では「ブレークポイントは600px」とあるので、スマホの幅を600pxと仮定していると思うのですが認識合っているでしょうか？
私が書いたCSSでは仕様通りブレークポイントを600pxにして、メインビジュアル(1920x1280の画像)以外の要素の幅を、課題にあるスクリーンショットと見た目が同じになるように350pxにしました。デベロッパーツールで幅を600pxにしたときの結果は画像のようになるのですが、これではスマホ対応にはなってないということでしょうか？
![image](https://github.com/yokoyamamn/hc_practice/assets/94735931/20833774-4c4a-4c50-8387-b71133e6cae9)

2023-07-25 08:45 UTC, ihatov08 commented
> @ihatov08 課題の仕様では「ブレークポイントは600px」とあるので、スマホの幅を600pxと仮定していると思うのですが認識合っているでしょうか？ 私が書いたCSSでは仕様通りブレークポイントを600pxにして、メインビジュアル(1920x1280の画像)以外の要素の幅を、課題にあるスクリーンショットと見た目が同じになるように350pxにしました。デベロッパーツールで幅を600pxにしたときの結果は画像のようになるのですが、これではスマホ対応にはなってないということでしょうか？ ![image](https://user-images.githubusercontent.com/94735931/255748398-20833774-4c4a-4c50-8387-b71133e6cae9.png)

@yokoyamamn 修正前時点ではヘッダーが崩れていたのですが、今確認したら治っていました！

2023-07-25 08:45 UTC, ihatov08 approved these changes
確認しました、LGTMです！

2023-07-25 08:51 UTC, yokoyamamn commented
@ihatov08 
承知いたしました！ご確認いただきありがとうございます！

2023-07-25 08:51 UTC, merged